### ISSUE TITLE
Selector lost when block applies to two selectors with comma

### ISSUE THREAD

**Issue by moll** [trevorblades/transform-css#6]
Hey,

The following generates wrong nested Less:

``` css
.arg-header,
.social-header{
    padding: 40px 0 20px;
}


.arg-header h2,
.social-header h2{
    font-size: 28px;
}
```

``` less
.social-header {
  padding: 40px 0 20px;
  h2 {
    font-size: 28px;
  }
}
```

`.arg-header` should be preserved.
